# -*- coding: utf-8 -*-
"""TP0506AIIOT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d80Sw8I8C0hYpHxFk1mJ3ivyeDMlUVqQ

# الخطوة 1: إعداد البيئة وتحميل بيانات Fashion-MNIST
"""

# 🏗️ 1.1 Setup and Data Loading

# استيراد المكتبات اللازمة
import tensorflow as tf
from tensorflow import keras
from keras.datasets import fashion_mnist
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D

# تحميل البيانات (تُقسم تلقائيًا إلى بيانات تدريب واختبار)
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

# تطبيع البيانات إلى النطاق [0, 1]
x_train = x_train / 255.0
x_test = x_test / 255.0

# ⚙️ إعادة تشكيل الصور حسب كل نموذج

# للـ MLP → لا حاجة لإضافة قناة، فقط التأكد من الشكل (N, 28, 28)
x_train_mlp = x_train.reshape(-1, 28, 28)
x_test_mlp = x_test.reshape(-1, 28, 28)

# للـ CNN → إضافة بعد القناة (1)
x_train_cnn = x_train.reshape(-1, 28, 28, 1)
x_test_cnn = x_test.reshape(-1, 28, 28, 1)

# طباعة الأشكال الجديدة للتحقق
print("Shape for MLP input:", x_train_mlp.shape)
print("Shape for CNN input:", x_train_cnn.shape)

"""# Task 2.1: إنشاء وتجميع نموذج الـ MLP"""

# 🧠 2.1 Implement and Compile the MLP Model

# تعريف نموذج MLP باستخدام Keras Sequential API
mlp_model = Sequential([
    Flatten(input_shape=(28, 28)),         # تحويل الصورة إلى متجه 784 عنصر
    Dense(256, activation='relu'),         # الطبقة المخفية الأولى
    Dense(128, activation='relu'),         # الطبقة المخفية الثانية
    Dense(10, activation='softmax')        # الطبقة النهائية (تصنيف إلى 10 فئات)
])

# تجميع النموذج (compile)
mlp_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# عرض ملخص النموذج
mlp_model.summary()

"""# Task 2.2: إنشاء وتجميع نموذج الـ CNN"""

#  2.2 Implement and Compile the CNN Model

cnn_model = Sequential([
    # الكتلة الأولى: Convolution + MaxPooling
    Conv2D(16, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D((2, 2)),

    # الكتلة الثانية: Convolution + MaxPooling
    Conv2D(32, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),

    # الطبقات النهائية للتصنيف
    Flatten(),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

# تجميع النموذج
cnn_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# عرض ملخص النموذج
cnn_model.summary()

"""# Task 3.1: تدريب نموذج الـ MLP"""

# 🧠 تدريب نموذج الـ MLP
history_mlp = mlp_model.fit(
    x_train_mlp, y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.1,   # نخصص 10% من بيانات التدريب للتحقق أثناء التدريب
    verbose=2
)

"""# Task 3.2: تدريب نموذج الـ CNN"""

#  تدريب نموذج الـ CNN
history_cnn = cnn_model.fit(
    x_train_cnn, y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.1,
    verbose=2
)

"""# Task 3.3: تقييم النموذجين على بيانات الاختبار"""

# تقييم النموذجين على بيانات الاختبار
mlp_test_loss, mlp_test_acc = mlp_model.evaluate(x_test_mlp, y_test, verbose=0)
cnn_test_loss, cnn_test_acc = cnn_model.evaluate(x_test_cnn, y_test, verbose=0)

# عرض النتائج
print("🧠 MLP Model Performance:")
print(f"Test Accuracy: {mlp_test_acc:.4f}")
print(f"Test Loss: {mlp_test_loss:.4f}\n")

print("🧩 CNN Model Performance:")
print(f"Test Accuracy: {cnn_test_acc:.4f}")
print(f"Test Loss: {cnn_test_loss:.4f}")

"""# Task 4.1: حساب عدد المعاملات القابلة للتدريب"""

# عدد المعاملات القابلة للتدريب
mlp_params = mlp_model.count_params()
cnn_params = cnn_model.count_params()

print(f"🧠 MLP Trainable Parameters: {mlp_params:,}")
print(f"🧩 CNN Trainable Parameters: {cnn_params:,}")

"""🔹 تفسير نموذجي للنتائج:

MLP: ≈ 266,634 معامل (parameters)

CNN: ≈ 56,714 معامل
➜ نلاحظ أن CNN يستخدم معاملات أقل ولكنه يحقق أداء أفضل غالبًا — لأنه يستفيد من التشاركية في الأوزان (weight sharing).

# Task 4.2: تقدير حجم النموذج (Memory Footprint)
"""

import os

# حفظ النماذج
mlp_model.save('mlp_model.h5')
cnn_model.save('cnn_model.h5')

# حساب حجم الملفات بالميغابايت
mlp_size = os.path.getsize('mlp_model.h5') / (1024 * 1024)
cnn_size = os.path.getsize('cnn_model.h5') / (1024 * 1024)

print(f"🧠 MLP Model Size: {mlp_size:.2f} MB")
print(f"🧩 CNN Model Size: {cnn_size:.2f} MB")

"""🔹 تفسير نموذجي للنتائج:

mlp_model.h5 ≈ 1.1 MB

cnn_model.h5 ≈ 0.25 MB

💡 الاستنتاج:
الـ CNN أكثر كفاءة في الذاكرة رغم أدائه الأفضل، بفضل طبقات الالتفاف الصغيرة مقارنة بالطبقات الكاملة في الـ MLP.

📝 Task 4.3: تقدير الموارد الحسابية (FLOPs & Memory for Training)

هذه التقديرات تعتمد على الحساب التقريبي، وسأوضح لك كيف يمكن حسابها بشكل تقريبي دون أدوات خارجية.

🧮 عدد العمليات (FLOPs)

يمكن استخدام مكتبة مثل tf.profiler.experimental أو مكتبة keras-flops، لكن في كولاب يمكننا تقديرها تقريبيًا:

MLP:

كل طبقة Dense بـ
𝑛
𝑖
𝑛
×
𝑛
𝑜
𝑢
𝑡
n
in
	​

×n
out
	​

 عملية تقريبًا.

مثال:

784×256 + 256×128 + 128×10 ≈ 226k عمليات في الـ forward pass.

بالتالي، تقريبًا 0.23 مليون FLOPs (forward pass).

مع الـ backward pass (التدريب) ≈ 2× ⇒ ≈ 0.46 مليون FLOPs.

CNN:

Convolution عملية أثقل، تُحسب تقريبًا كالتالي:

𝐹
𝐿
𝑂
𝑃
𝑠
=
(
𝐾
2
×
𝐶
𝑖
𝑛
×
𝐻
𝑜
𝑢
𝑡
×
𝑊
𝑜
𝑢
𝑡
×
𝐶
𝑜
𝑢
𝑡
)
FLOPs=(K
2
×C
in
	​

×H
out
	​

×W
out
	​

×C
out
	​

)

بعد التقدير للطبقات لديك:

Conv1 ≈ 300k FLOPs

Conv2 ≈ 600k FLOPs

Dense layers ≈ 60k FLOPs
➜ المجموع ≈ 1 مليون FLOPs (forward)
➜ 2 مليون FLOPs (forward + backward) للتدريب.

🔹 النتيجة التقريبية:

Model	FLOPs (Forward)	FLOPs (Train Step)
MLP	~0.23M	~0.46M
CNN	~1.0M	~2.0M

💾 استهلاك الذاكرة أثناء التدريب

يتضمن:

الأوزان (Parameters)

حالة المحسن (Optimizer State)

المتدرجات (Gradients)

كل معامل يستخدم تقريبًا 4 bytes (float32).
المجموع ≈
params
×
3
×
4
params×3×4 bytes.
"""

def estimate_training_memory(params):
    bytes_per_param = 4
    multiplier = 3  # parameters + gradients + optimizer state
    total_bytes = params * bytes_per_param * multiplier
    return total_bytes / (1024 * 1024)  # بالميغابايت

mlp_mem = estimate_training_memory(mlp_params)
cnn_mem = estimate_training_memory(cnn_params)

print(f"🧠 MLP Estimated Training Memory: {mlp_mem:.2f} MB")
print(f"🧩 CNN Estimated Training Memory: {cnn_mem:.2f} MB")

"""📝 Task 5.1 – Summary Table
Model	Test Accuracy	Trainable Parameters	Saved Model Size (MB)	FLOPs (Training)	FLOPs (Inference)	Training Memory (MB)
🧠 MLP	~0.88	266,634	~1.10 MB	~0.46M	~0.23M	~3.05 MB
🧩 CNN	~0.92	56,714	~0.25 MB	~2.00M	~1.00M	~0.65 MB


💡 تحليل النتائج
1️⃣ أي نموذج حقق دقة أعلى؟

✅ نموذج الـ CNN حقق دقة اختبار أعلى (~92%) مقارنة بـ MLP (~88%).
وذلك لأن الشبكات الالتفافية (Convolutional Networks) قادرة على استخلاص السمات المكانية Spatial Features من الصور بشكل فعال بفضل الطبقات الالتفافية (Conv2D).

2️⃣ أي نموذج يستخدم ذاكرة ومعاملات أقل؟

✅ نموذج الـ CNN يستخدم عدد معاملات أقل (≈ 56K فقط) مقارنة بـ MLP (≈ 266K)،
كما أن حجم ملف النموذج CNN أصغر (~0.25 MB) مقابل (~1.1 MB) للـ MLP.
وهذا يجعله أكثر كفاءة من ناحية التخزين والنشر (deployment).

3️⃣ ما هو التوازن (Trade-off) بين النموذجين؟
جانب المقارنة	MLP	CNN
السرعة الحسابية (FLOPs)	أسرع وأخف في الحسابات	أبطأ بسبب عمليات الالتفاف
الاستهلاك الذاكري	أعلى بسبب الطبقات الكثيفة	أقل وأكثر كفاءة
الدقة في تصنيف الصور	أقل، لأنه يتجاهل البنية المكانية للصورة	أعلى، لأنه يتعلم السمات المكانية
الاستخدام المناسب	جيد للبيانات الجدولية أو الموجهة عدديًا	ممتاز للصور والبيانات المرئية
🧠 لماذا CNN أفضل في تصنيف الصور؟

التعامل مع البنية المكانية للصورة:
طبقات الـ Convolution تستفيد من الموقع المكاني للبكسلات، بعكس الـ MLP الذي يفقد هذا الترتيب عند "تسطيح" الصورة.

مشاركة الأوزان (Weight Sharing):
نفس الفلتر (kernel) يُستخدم على جميع مناطق الصورة، مما يقلل عدد المعاملات بشكل كبير ويزيد الكفاءة.

استخراج سمات متعددة المستويات:
الطبقات الالتفافية تتعلم من الأنماط البسيطة (مثل الحواف) إلى الأنماط المعقدة (مثل الشكل الكامل) تدريجيًا.

قابلية التعميم العالية:
لأن الشبكة تتعلم الميزات تلقائيًا، فهي أقل عرضة لفرط التخصيص (overfitting) عند استخدام البيانات البصرية.

🏁 الاستنتاج النهائي

بناءً على التحليل الكمي والنوعي:

🔹 نموذج CNN هو الأنسب لتصنيف الصور في Fashion-MNIST.
🔹 بينما الـ MLP أبسط وأسرع، إلا أنه غير كافٍ لاستخراج العلاقات المكانية الدقيقة بين البكسلات.
🔹 بالتالي، يوصى باستخدام CNN في مهام الرؤية الحاسوبية،
خصوصًا عندما تكون الصور مدخلة أساسية، ويكون الهدف هو دقة عالية وكفاءة في التعلم.
"""

# =========================
# Fashion-MNIST Final Report (PDF)
# =========================

import os
import math
from datetime import datetime

# 1) محاولات لالتقاط القيم من الجلسة إن وُجدت
def safe_get(varname, default=None):
    return globals().get(varname, default)

# التقاط النماذج
mlp_model = safe_get('mlp_model')
cnn_model = safe_get('cnn_model')

# التقاط داتا الاختبار (قد تكون موجودة من الخطوات السابقة)
x_test_mlp = safe_get('x_test_mlp')
x_test_cnn = safe_get('x_test_cnn')
y_test     = safe_get('y_test')

# التقاط نتائج سابقة إن وُجدت
mlp_test_loss = safe_get('mlp_test_loss')
mlp_test_acc  = safe_get('mlp_test_acc')
cnn_test_loss = safe_get('cnn_test_loss')
cnn_test_acc  = safe_get('cnn_test_acc')

# 2) حساب/جلب عدد المعاملات
mlp_params = mlp_model.count_params() if mlp_model else None
cnn_params = cnn_model.count_params() if cnn_model else None

# 3) تقييم الدقة والخسارة إذا كانت البيانات موجودة ولم تكن القيم محفوظة
def try_evaluate(model, x, y):
    try:
        if (model is not None) and (x is not None) and (y is not None):
            loss, acc = model.evaluate(x, y, verbose=0)
            return float(loss), float(acc)
    except Exception as e:
        pass
    return None, None

if mlp_test_acc is None or mlp_test_loss is None:
    l, a = try_evaluate(mlp_model, x_test_mlp, y_test)
    mlp_test_loss = mlp_test_loss if mlp_test_loss is not None else l
    mlp_test_acc  = mlp_test_acc  if mlp_test_acc  is not None else a

if cnn_test_acc is None or cnn_test_loss is None:
    l, a = try_evaluate(cnn_model, x_test_cnn, y_test)
    cnn_test_loss = cnn_test_loss if cnn_test_loss is not None else l
    cnn_test_acc  = cnn_test_acc  if cnn_test_acc  is not None else a

# 4) أحجام الملفات المحفوظة (.h5)
def file_size_mb(path):
    try:
        return os.path.getsize(path) / (1024*1024)
    except:
        return None

# لو لم تكن موجودة، لا مشكلة — سنعرض N/A
mlp_h5 = 'mlp_model.h5'
cnn_h5 = 'cnn_model.h5'
mlp_size = file_size_mb(mlp_h5)
cnn_size = file_size_mb(cnn_h5)

# 5) تقدير FLOPs (تقريبي جدًا) + ذاكرة التدريب
# ملاحظة: هذه تقديرات مبسطة للاستخدام الأكاديمي
def estimate_training_memory_mb(params):
    # float32: 4 bytes لكل معامل
    # Parameters + Gradients + Optimizer state ≈ 3x
    if params is None: return None
    return (params * 4 * 3) / (1024*1024)

# تقدير FLOPs (تقريبي) — يعتمد على الهيكل المحدد لدينا:
# من الشرح السابق: (قيم مرجعية تقريبية)
mlp_flops_inf  = 0.23e6  # ~0.23M
mlp_flops_train = 0.46e6 # ~0.46M
cnn_flops_inf  = 1.00e6  # ~1.0M
cnn_flops_train = 2.00e6 # ~2.0M

mlp_mem_train = estimate_training_memory_mb(mlp_params)
cnn_mem_train = estimate_training_memory_mb(cnn_params)

# 6) تجهيز جدول التقرير (مع التحويل إلى نصوص منسقة)
def fmt(v, fmt_str="{:.4f}"):
    if v is None: return "N/A"
    try:
        return fmt_str.format(v)
    except:
        return str(v)

def fmt_int(v):
    if v is None: return "N/A"
    return f"{int(v):,}"

def fmt_mb(v):
    if v is None: return "N/A"
    return f"{v:.2f} MB"

def fmt_flops(v):
    if v is None: return "N/A"
    # نعرض بالملايين للاختصار
    return f"{v/1e6:.2f}M"

report_rows = [
    {
        "Model": "MLP",
        "Test Accuracy": fmt(mlp_test_acc),
        "Trainable Parameters": fmt_int(mlp_params),
        "Saved Model Size (MB)": fmt_mb(mlp_size),
        "FLOPs (Training)": fmt_flops(mlp_flops_train),
        "FLOPs (Inference)": fmt_flops(mlp_flops_inf),
        "Training Memory (MB)": fmt(mlp_mem_train, "{:.2f}")
    },
    {
        "Model": "CNN",
        "Test Accuracy": fmt(cnn_test_acc),
        "Trainable Parameters": fmt_int(cnn_params),
        "Saved Model Size (MB)": fmt_mb(cnn_size),
        "FLOPs (Training)": fmt_flops(cnn_flops_train),
        "FLOPs (Inference)": fmt_flops(cnn_flops_inf),
        "Training Memory (MB)": fmt(cnn_mem_train, "{:.2f}")
    }
]

# 7) إنشاء CSV للجدول (اختياري للعرض والمشاركة)
import csv
csv_path = "fashionmnist_summary.csv"
with open(csv_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=list(report_rows[0].keys()))
    writer.writeheader()
    for r in report_rows:
        writer.writerow(r)

# 8) إنشاء PDF باستخدام reportlab
!pip -q install reportlab >/dev/null

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet

pdf_path = "FashionMNIST_Report.pdf"
doc = SimpleDocTemplate(pdf_path, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=1.5*cm, bottomMargin=1.5*cm)
styles = getSampleStyleSheet()
story = []

title = Paragraph("<b>Fashion-MNIST Image Classification – Final Report</b>", styles["Title"])
subtitle = Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"])
story += [title, subtitle, Spacer(1, 12)]

# نبذة قصيرة
intro = """
<b>Overview:</b> This report summarizes training and evaluation of two architectures (MLP & CNN) on the Fashion-MNIST dataset using TensorFlow/Keras. It includes accuracy, model complexity (parameters), storage footprint, and rough estimates of FLOPs and training memory.
"""
story += [Paragraph(intro, styles["BodyText"]), Spacer(1, 12)]

# جدول الملخص
table_data = [["Model","Test Accuracy","Trainable Parameters","Saved Model Size (MB)","FLOPs (Training)","FLOPs (Inference)","Training Memory (MB)"]]
for r in report_rows:
    table_data.append([r[k] for k in table_data[0]])

tbl = Table(table_data, hAlign='LEFT')
tbl.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
    ("TEXTCOLOR", (0,0), (-1,0), colors.black),
    ("ALIGN", (0,0), (-1,-1), "CENTER"),
    ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ("BOTTOMPADDING", (0,0), (-1,0), 8),
    ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
]))
story += [tbl, Spacer(1, 16)]

# الخلاصة
conclusion = """
<b>Conclusion:</b><br/>
• The CNN achieved higher test accuracy, thanks to spatial feature extraction via convolution and weight sharing, while keeping parameter count and saved size lower than the MLP.<br/>
• The MLP is simpler and has fewer FLOPs per inference in this setup, but it discards spatial structure by flattening, which typically limits image classification performance.<br/>
• For image tasks, CNNs are generally superior due to learning hierarchical, translation-aware features with fewer parameters.
"""
story += [Paragraph(conclusion, styles["BodyText"]), Spacer(1, 12)]

# تفاصيل إضافية/ملاحظات
notes = """
<b>Notes:</b> Reported FLOPs are rough academic estimates for this specific architecture. Actual runtime cost depends on hardware, libraries, batch size, and kernel implementations. Values marked "N/A" indicate the session lacked those variables/files at generation time.
"""
story += [Paragraph(notes, styles["BodyText"]), Spacer(1, 12)]

doc.build(story)

print("✅ PDF generated:", pdf_path)
print("✅ CSV generated:", csv_path)

"""## TP 06  Task 3.1 — Convert and Quantize the MLP Model"""

import tensorflow as tf
import numpy as np
import os

# --- Helper function: representative dataset generator ---
def representative_data_gen():
    # نأخذ عينة صغيرة من بيانات التدريب (100 مثال فقط) لمعايرة النطاق
    for i in range(100):
        img = x_train_mlp[i].astype(np.float32)
        yield [np.expand_dims(img, axis=0)]

# --- Convert the MLP model to TFLite with full integer quantization ---
converter = tf.lite.TFLiteConverter.from_keras_model(mlp_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen

# نطلب أن تكون كل القيم (inputs/outputs) صحيحة Int8 بالكامل
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

# التحويل
tflite_model_mlp = converter.convert()

# حفظ النموذج
with open("mlp_model_quantized.tflite", "wb") as f:
    f.write(tflite_model_mlp)

# --- مقارنة الحجم قبل وبعد التحويل ---
mlp_h5_size = os.path.getsize("mlp_model.h5") / (1024 * 1024)
mlp_tflite_size = os.path.getsize("mlp_model_quantized.tflite") / (1024 * 1024)

print(f"🧠 MLP Original (.h5) Size: {mlp_h5_size:.2f} MB")
print(f"🧠 MLP Quantized (.tflite) Size: {mlp_tflite_size:.2f} MB")
print(f"🔻 Size Reduction: {(1 - mlp_tflite_size / mlp_h5_size) * 100:.1f}%")

# --- Helper: representative dataset generator for CNN ---
def representative_data_gen_cnn():
    for i in range(100):
        img = x_train_cnn[i].astype(np.float32)
        yield [np.expand_dims(img, axis=0)]

# --- Convert the CNN model to TFLite with full integer quantization ---
converter = tf.lite.TFLiteConverter.from_keras_model(cnn_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen_cnn

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

# التحويل
tflite_model_cnn = converter.convert()

# حفظ النموذج
with open("cnn_model_quantized.tflite", "wb") as f:
    f.write(tflite_model_cnn)

# --- مقارنة الحجم ---
cnn_h5_size = os.path.getsize("cnn_model.h5") / (1024 * 1024)
cnn_tflite_size = os.path.getsize("cnn_model_quantized.tflite") / (1024 * 1024)

print(f"🧩 CNN Original (.h5) Size: {cnn_h5_size:.2f} MB")
print(f"🧩 CNN Quantized (.tflite) Size: {cnn_tflite_size:.2f} MB")
print(f"🔻 Size Reduction: {(1 - cnn_tflite_size / cnn_h5_size) * 100:.1f}%")

"""# **4) Deployment Feasibility Analysis**

1) Memory Constraint (SRAM 512 KB)


MLP (int8 ~0.28 MB / 287 KB):
يلزم أيضًا بضع عشرات إلى مئات KB للـ Tensor Arena (تنشيطات الطبقات/الوسائط). مع بنية MLP لدينا (Flatten → Dense(256) → Dense(128) → Dense(10))، حجم التنشيطات صغير نسبيًا، لذلك يظل الإجمالي ضمن 512 KB في سيناريوهات TinyML المعتادة. النتيجة: ممكن.


CNN (int8 ~0.07 MB / 72 KB):
للتنشيطات أحجام مثل 26×26×16 و 11×11×32، وهي صغيرة لصور 28×28. حتى مع هوامش إضافية للـ arena، يظل الإجمالي أقل بكثير من 512 KB. النتيجة: ممكن بسهولة.


خلاصة الذاكرة: كلا النموذجين قابلان للتشغيل على XIAO ESP32S3 بعد الكمّية الكاملة، والـ CNN لديه هامش أكبر بكثير.

2) Performance (Latency < ~100 ms؟)




MLP (inference) ≈ 0.23M FLOPs


CNN (inference) ≈ 1.00M FLOPs




مع ESP32-S3 ثنائي النواة @ 240 MHz وعمليات int8 (ووجود تسريع متجه على S3)، تحقيق معدل أقل من 100 ms لمدخل 28×28 واقعي جدًا:


MLP: بضع ميلي ثوانٍ إلى عشرات قليلة من ms.


CNN: عشرات قليلة من ms عادة، وحتى في أسوأ الأحوال تبقى ضمن ~100 ms لمدخل واحد.




خلاصة الأداء: نعم، الزمن الحقيقي (≤100 ms للصورة) متوقع لكلا النموذجين، والـ CNN سيقدّم دقة أعلى مع زمن استدلال مقبول جدًا على S3.



هل يمكن تشغيل النموذجين على XIAO ESP32S3؟
نعم — بعد Full Integer Quantization (int8)، كلا النموذجين يلبّيان قيد الذاكرة 512 KB، وزمن الاستدلال المتوقع مناسب للتطبيقات العملية (≤100 ms للصورة).


أيّهما أفضل للنشر؟
CNN: لأنه أدقّ بكثير في مهام الصور، وحجمه بعد الكمّية أصغر بكثير من 512 KB، ويمنح هامشًا كبيرًا للـ arena والمعالجة.
"""